name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: reviewdog/action-setup@v1.0.3
        with:
          reviewdog_version: latest

      - name: prepare
        run: npm ci

      - name: lint
        uses: mooyoul/tslint-actions@v1.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'

      - name: type check
        run: tsc --pretty false --noEmit | reviewdog -f=tsc -reporter=github-pr-review -fail-on-error=true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: npm run build
