name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: reviewdog/action-setup@v1.0.3
        with:
          reviewdog_version: latest

      - name: prepare
        run: npm ci

      - name: lint
        uses: reviewdog/action-eslint@v1.24.0
        id: "lint"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      - name: typecheck
        # typecheck even if lint fails
        if: ${{ !cancelled() }}
        run: tsc --pretty false --noEmit | reviewdog -f=tsc -reporter=github-pr-review -fail-on-error=true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: npm run build
